language: rust
rust:
  - stable
  - nightly
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.6
      - python3.6-dev
matrix:
  allow_failures:
    - rust: stable
  fast_finish: true
