[package]
name = "newick"
version = "0.1.0"
authors = ["Stephan Heijl <sheijl@bio-prodict.nl>"]

[dependencies]
ndarray = { version = "0.12.1" }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.0"
rayon = "1.0"
petgraph = "0.4.13"
regex = "1"

[features]
singlecore = []