[package]
name = "newick"
version = "0.1.0"
authors = ["Stephan Heijl <sheijl@bio-prodict.nl>"]

[dependencies]
ndarray = "0.12.1"
rayon = "1.0"
petgraph = "0.4.13"
regex = "1"

[features]
singlecore = []