[package]
name = "global-supertrees"
version = "0.1.0"
authors = ["Stephan Heijl <sheijl@bio-prodict.nl>"]
license = " CC-BY-NC-SA-4.0"
description = "A package containing code for generating global supertrees from protein alignment trees."

[dependencies]
ndarray = { version = "0.12.1" }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.0"
rayon = "1.0"
petgraph = "0.4.13"
regex = "1"

[features]
singlecore = []